# Generated by Django 5.2.3 on 2025-06-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=20)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('observacao', models.TextField(blank=True, default='')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total_com_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamento.orcamento')),
            ],
        ),
    ]
