# Generated by Django 5.2.3 on 2025-06-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientes_apto_bloco_alter_clientes_nome_and_more'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='clientes.clientes'),
        ),
    ]
