# Generated by Django 5.2.3 on 2025-06-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_orcamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado'), ('pendente_pagamento', 'Pendente de Pagamento'), ('PAGO', 'PAGO')], default='aberto', max_length=20),
        ),
    ]
