# Generated by Django 5.2.3 on 2025-06-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
        ('orcamento', '0003_alter_orcamento_status'),
        ('rat', '0005_alter_rat_options_remove_rat_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='valor_desconto',
            new_name='sla_resposta',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_total_com_desconto',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_acionamento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_chegada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='nome_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_local', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='nome_usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_local', to='rat.rat'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ItemOrcamento',
        ),
    ]
