# Generated by Django 5.2.3 on 2025-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_rename_valor_desconto_orcamento_sla_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_acionamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_chegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
