# Generated by Django 5.2.3 on 2025-06-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
        ('orcamento', '0005_alter_orcamento_data_acionamento_and_more'),
        ('rat', '0005_alter_rat_options_remove_rat_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_acionamento'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='numero',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_local', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome_usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_usuario', to='rat.rat'),
        ),
    ]
