# Generated by Django 5.2.3 on 2025-06-27 19:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_alter_orcamento_options_remove_orcamento_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='sla_resposta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
