# Generated by Django 5.2.3 on 2025-07-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_alter_orcamento_sla_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='orcamentos/', verbose_name='Imagem'),
        ),
    ]
