# Generated by Django 5.2.3 on 2025-06-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rat', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('data_visita', models.DateField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rg_inscricao', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('loja_revendedora', models.CharField(blank=True, max_length=200, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('equipamento', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('diametro_tubulacao', models.CharField(blank=True, max_length=50, null=True)),
                ('voltagem', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_gas', models.CharField(blank=True, max_length=100, null=True)),
                ('equipe_tecnica', models.CharField(blank=True, max_length=200, null=True)),
                ('relatorio_interno', models.TextField(blank=True, null=True)),
                ('servico_executar', models.TextField(blank=True, null=True)),
                ('tipo_servico', models.CharField(choices=[('instalacao', 'Instalação'), ('garantia', 'Garantia'), ('corretiva', 'Corretiva')], default='instalacao', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório de Manutenção',
                'verbose_name_plural': 'Relatórios de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
    ]
