# Generated by Django 5.2.3 on 2025-06-22 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=100, verbose_name='Nome da Peça')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Compra')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
