# Generated by Django 5.2.3 on 2025-06-22 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['-id'], 'verbose_name': 'Item de Estoque', 'verbose_name_plural': 'Itens de Estoque'},
        ),
        migrations.AddField(
            model_name='estoque',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='status',
            field=models.CharField(choices=[('ESTOQUE', 'Estoque'), ('GARANTIA', 'Garantia')], default='ESTOQUE', max_length=20, verbose_name='Solicitação'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código do produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Informações sobre a Peça'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='nome_peca',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
