# Generated by Django 5.2.3 on 2025-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_options_estoque_modelo_estoque_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('reservado', 'Reservado')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
    ]
