# Generated by Django 5.2.3 on 2025-06-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
        ('estoque', '0003_alter_estoque_status'),
        ('rat', '0005_alter_rat_options_remove_rat_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={},
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='nome_peca',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='preco_compra',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='estoque',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_agenda', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_agenda', to='rat.rat'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='status',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('programado', 'Programado'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
    ]
