# Generated by Django 5.1.2 on 2025-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_estoque_options_remove_estoque_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_produto', models.CharField(choices=[('Camera', 'Câmera'), ('Botao de panico', 'Botão de pânico'), ('MDVR', 'MDVR')], max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
