# Generated by Django 5.1.2 on 2025-07-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
    ]
