# Generated by Django 5.1.2 on 2025-07-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_produto_tipo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
