# Generated by Django 5.2.3 on 2025-07-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Disponível'),
        ),
        migrations.CreateModel(
            name='Licencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade de Licenças')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Licença')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='estoque.produto', verbose_name='Produto')),
            ],
        ),
    ]
