# Generated by Django 5.2.3 on 2025-07-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_produto_quantidade_licencas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usos_estoque', to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade Usada'),
        ),
    ]
