# Generated by Django 5.2.3 on 2025-06-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_clientes_apto_bloco_alter_clientes_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rat', models.CharField(max_length=50, unique=True, verbose_name='Número da RAT')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data_visita', models.DateField(blank=True, null=True, verbose_name='Data da Visita')),
                ('periodo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Período')),
                ('horario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data da Instalação')),
                ('loja_revendedora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loja Revendedora')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('codigo_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto')),
                ('diametro_tubulacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diâmetro da Tubulação')),
                ('voltagem', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Nota Fiscal')),
                ('tipo_gas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Gás')),
                ('equipe_tecnica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipe Técnica')),
                ('tipo_servico', models.CharField(blank=True, choices=[('garantia', 'Garantia'), ('corretiva', 'Corretiva')], max_length=20, null=True, verbose_name='Tipo de Serviço')),
                ('relatorio_interno', models.TextField(blank=True, null=True, verbose_name='Relatório Interno de Atendimentos Executados')),
                ('servico_a_executar', models.TextField(blank=True, null=True, verbose_name='Serviço a Executar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rats', to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'RAT',
                'verbose_name_plural': 'RATs',
                'ordering': ['-data_visita'],
            },
        ),
    ]
