# Generated by Django 5.2.3 on 2025-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0003_alter_rat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('pendente_pagamento', 'Pendente de Pagamento'), ('PAGO', 'PAGO')], default='aberto', max_length=20),
        ),
    ]
