# Generated by Django 5.2.3 on 2025-06-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
        ('rat', '0004_alter_rat_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rat',
            options={'verbose_name': 'RAT', 'verbose_name_plural': 'RATs'},
        ),
        migrations.RemoveField(
            model_name='rat',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='codigo_produto',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='data_compra',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='data_instalacao',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='data_visita',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='diametro_tubulacao',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='equipe_tecnica',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='loja_revendedora',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='numero_nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='numero_rat',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='relatorio_interno',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='servico_a_executar',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='tipo_gas',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='tipo_servico',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rat',
            name='voltagem',
        ),
        migrations.AddField(
            model_name='rat',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rat',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='rat',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Usuario'),
        ),
    ]
