# Generated by Django 5.2.3 on 2025-06-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('dia_semana', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('servico', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('profissional', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='agenda.agendadia')),
            ],
        ),
    ]
