# Generated by Django 5.2.3 on 2025-06-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('realizado', 'Realizado'), ('programado', 'Programado'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_pendentes', to='clientes.clientes')),
            ],
        ),
    ]
