# Generated by Django 5.2.3 on 2025-06-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
        ('rat', '0005_alter_rat_options_remove_rat_cliente_and_more'),
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treinamento',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='duracao_horas',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='instrutor',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='treinamento',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rat.rat'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('programado', 'Programado'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
    ]
