# Generated by Django 5.2.3 on 2025-06-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('portas_abertas', 'Portas e Portões Abertos'), ('inibicao_cameras', 'Inibição de Câmeras e Sensores'), ('botao_panico', 'Acionamento indevido de Botão de Pânico')], default='portas_abertas', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
    ]
