# Generated by Django 5.2.3 on 2025-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ocorrencias/', verbose_name='Imagem'),
        ),
    ]
