# Generated by Django 5.1.2 on 2025-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='status_servico',
            field=models.CharField(blank=True, choices=[('agendado', 'Agendado'), ('pendente_pagamento', 'Pendente de Pagamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=50, null=True),
        ),
    ]
