# Generated by Django 5.1.2 on 2025-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_options_alter_clientes_status_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='servicos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
