# Generated by Django 5.1.2 on 2025-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='apto_bloco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='relatorios_servicos_prestados',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='servicos',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
