# Generated by Django 5.2.3 on 2025-06-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientes_apto_bloco_alter_clientes_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='status_servico',
            field=models.CharField(blank=True, choices=[('agendado', 'Agendado'), ('pendente_pagamento', 'Pendente de Pagamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('PAGO', 'PAGO')], default='agendado', max_length=50, null=True),
        ),
    ]
