# Generated by Django 5.1.2 on 2025-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
