# Generated by Django 5.1.2 on 2025-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_clientes_quantidade_clientes_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_produto',
            field=models.CharField(blank=True, choices=[('Camera', 'Câmera'), ('Botao de panico', 'Botão de pânico'), ('MDVR', 'MDVR')], max_length=100, null=True),
        ),
    ]
