# Generated by Django 5.1.2 on 2025-07-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_clientes_tipo_produto'),
        ('estoque', '0006_remove_produto_tipo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='tipo_produto',
        ),
        migrations.AddField(
            model_name='clientes',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='estoque.produto'),
        ),
    ]
