# Generated by Django 5.1.2 on 2025-07-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_clienteproduto'),
        ('estoque', '0007_remove_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ClienteProduto',
        ),
    ]
