# Generated by Django 5.1.2 on 2025-07-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_clientes_produto_alter_clientes_quantidade_and_more'),
        ('estoque', '0007_remove_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_relacionados', to='clientes.clientes')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'unique_together': {('cliente', 'produto')},
            },
        ),
    ]
