# Generated by Django 5.1.2 on 2025-07-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_clienteproduto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='quantidade',
        ),
    ]
