# Generated by Django 5.2.3 on 2025-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_clientes_options_remove_clientes_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='pronta_resposta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pronta Resposta'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
