# Generated by Django 5.2.3 on 2025-07-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_clientes_pronta_resposta_clientes_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProntaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronta_resposta', models.CharField(max_length=200, verbose_name='Pronta Resposta')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontas_respostas', to='clientes.clientes')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('cliente', 'pronta_resposta')},
            },
        ),
        migrations.CreateModel(
            name='ClienteTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo (ex: Celular, Fixo)')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='clientes.clientes')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('cliente', 'telefone')},
            },
        ),
    ]
