# Generated by Django 5.2.3 on 2025-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_clienteprontaresposta_clientetelefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável'),
        ),
    ]
