# Generated by Django 5.2.3 on 2025-06-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orpecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Nº Orçamento')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total_com_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orçamento de Peça',
                'verbose_name_plural': 'Orçamentos de Peças',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrpecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orpecas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orpecas.orpecas')),
            ],
        ),
    ]
