# Generated by Django 5.2.3 on 2025-06-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_clientes_apto_bloco_remove_clientes_bairro_and_more'),
        ('orpecas', '0002_alter_orpecas_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orpecas',
            options={},
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='data',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='valor_desconto',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='orpecas',
            name='valor_total_com_desconto',
        ),
        migrations.AddField(
            model_name='orpecas',
            name='botao_panico',
            field=models.CharField(blank=True, choices=[('Intrusão', 'Intrusão'), ('Ameaça', 'Ameaça'), ('Pessoa Suspeita', 'Pessoa Suspeita')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orpecas',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('Intrusão', 'Intrusão'), ('Ameaça', 'Ameaça'), ('Pessoa Suspeita', 'Pessoa Suspeita')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orpecas',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrpecasLocal', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='orpecas',
            name='sensor',
            field=models.CharField(blank=True, choices=[('Intrusão', 'Intrusão'), ('Ameaça', 'Ameaça'), ('Pessoa Suspeita', 'Pessoa Suspeita')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ItemOrpecas',
        ),
    ]
