# Generated by Django 5.2.3 on 2025-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orpecas', '0003_alter_orpecas_options_remove_orpecas_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orpecas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='orpecas/', verbose_name='Imagem'),
        ),
    ]
